[phases.setup]
nixPkgs = ['python311', 'postgresql']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'python -m pip install -r requirements.txt']

[start]
cmd = 'cd backend && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT'
