[phases.setup]
nixPkgs = ['python312', 'postgresql']

[phases.install]
cmds = ['pip install -r backend/requirements.txt']

[phases.build]
cmds = ['cd backend && alembic upgrade head || echo "Migrations will run on start"']

[start]
cmd = 'cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT'
